server:
  port: 9000

eureka:  instance:    hostname: localhost
  client:    service-url:
        defaultzone: http://localhost:8761/eureka          
    
spring:  application:    name: API GATEWAY
  cloud:
    config:      import-check:
        enabled : false    gateway:
      routes:      - id: user-service
        uri: lb://user-management
        predicates:        - Path=/user/**
      - id: job-service
        uri: lb://job-portal
        predicates:
        - Path=/job/**
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
    #spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true 